#!/usr/bin/env python3
"""Generate docs/widgets.md (widget and metric reference) from the code."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from turzx.render.layout import cards  # noqa: E402,F401  (registers the card widget)
from turzx.render.widgets import WIDGETS  # noqa: E402
from turzx.sensors import METRICS  # noqa: E402


def main() -> None:
    out = [
        "# Widget and metric reference",
        "",
        "Generated by `tools/make_docs.py` from the widget schemas; do not edit by hand.",
        "",
        "Every widget also has the common fields `opacity`, `glow` and `glow_color` (group *Effects*).",
        "",
    ]
    for cls in WIDGETS.values():
        out += [f"## {cls.title} (`{cls.type}`)", "", cls.description, "",
                f"Category: {cls.category}. Default size: {cls.default_size[0]}×{cls.default_size[1]}.", "",
                "| Field | Kind | Default | Notes |", "|---|---|---|---|"]
        for f in cls.fields:
            default = f"`{f.default!r}`" if f.default not in ("", None) else ""
            notes = f.help
            if f.kind == "choice":
                notes = (notes + " " if notes else "") + "One of: " + ", ".join(f"`{v}`" for v, _ in f.choices())
            out.append(f"| `{f.key}` ({f.label}) | {f.kind} | {default} | {notes} |")
        out.append("")
    out += ["## Metrics", "", "Use these keys in templates (`{cpu.util}`) and in metric fields.", "",
            "| Key | Description | Unit | Kind |", "|---|---|---|---|"]
    for key, d in METRICS.items():
        out.append(f"| `{key}` | {d.label} | {d.unit} | {d.kind} |")
    out.append("| `cpu.cores` | Per-thread usage list (used by the CPU threads widget) | % | list |")
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "widgets.md").write_text("\n".join(out) + "\n")
    print("wrote docs/widgets.md")


if __name__ == "__main__":
    main()
